---
# tasks file for ansible-role-jenkins-slave

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include_vars: sample_secret.yml

- name: Create .ssh
  file:
    path: "{{ jenkins_slave_home }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"

- name: Create .ssh/authorized_keys
  template:
    src: authorized_keys.j2
    dest: "{{ jenkins_slave_home }}/.ssh/authorized_keys"
    mode: 0600
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
    validate: ssh-keygen -l -f %s

- name: Create .ansible_vault_key
  template:
    src: ansible_vault_key.j2
    dest: "{{ jenkins_slave_home }}/.ansible_vault_key"
    mode: 0600
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
